### PR TITLE
Remove no-inner-declarations

### PR DESCRIPTION
**Pull request by mightyiam**

### CODE REVIEW

**Comment by mightyiam** [comment]
Should I merge it? If yes, you might as well.

**Comment by feross** [comment]
No, please don't merge. I want to leave `master` in a shippable state for 14.x updates. When I'm ready to release 15.0.0, I'll merge all the PRs at once.

**Review by feross — APPROVED** [review]

**Comment by feross** [comment]
This will ship in standard v15

**Comment by feross** [comment]
Related: https://github.com/standard/standard/issues/1406

**Pull request merged**
