### PR TITLE
Add the array-bracket-spacing rule

### PR DESCRIPTION
**Pull request by flipxfx**
Per discussion here 
https://github.com/standard/standard/issues/609#issuecomment-419025829 and issue here https://github.com/standard/standard/issues/1203, add "array-bracket-spacing" rule set to "never".

### CODE REVIEW

**Comment by flipxfx** [comment]
Anyone want to approve the merge request? Simple change that was already approved in the issues.

**Comment by justinkalland** [comment]
Running this on the ecosystem causes 28 to fail. I also had to `--fix` on Standard itself to get tests to pass.

```
{
  "extends": ["standard", "standard-jsx"],
  "rules": {
    "array-bracket-spacing": ["error", "never"]
  }
}

1..186
# tests 186
# pass  158
# fail  28
```

Here are the failing repos:
- [ ] [semistandard](https://github.com/Flet/semistandard)
- [ ] [parse-torrent](https://github.com/webtorrent/parse-torrent)
- [ ] [buffer](https://github.com/feross/buffer)
- [ ] [virtual-element](https://github.com/dekujs/virtual-element)
- [ ] [re-emitter](https://github.com/feross/re-emitter)
- [ ] [webtorrent](https://github.com/webtorrent/webtorrent)
- [ ] [run-waterfall](https://github.com/feross/run-waterfall)
- [ ] [glob-promise](https://github.com/ahmadnassri/glob-promise)
- [ ] [magnet-uri](https://github.com/webtorrent/magnet-uri)
- [ ] [standard-engine](https://github.com/flet/standard-engine)
- [ ] [bittorrent-dht](https://github.com/webtorrent/bittorrent-dht)
- [ ] [bittorrent-tracker](https://github.com/webtorrent/bittorrent-tracker)
- [ ] [hosted-git-info](https://github.com/npm/hosted-git-info)
- [ ] [deglob](https://github.com/flet/deglob)
- [ ] [create-torrent](https://github.com/webtorrent/create-torrent)
- [ ] [blob-to-buffer](https://github.com/feross/blob-to-buffer)
- [ ] [prefix-style](https://github.com/mattdesl/prefix-style)
- [ ] [standard-packages](https://github.com/standard/standard-packages)
- [ ] [npm-install-package](https://github.com/yoshuawuyts/npm-install-package)
- [ ] [chrome-dgram](https://github.com/feross/chrome-dgram)
- [ ] [markdown-it-decorate](https://github.com/rstacruz/markdown-it-decorate)
- [ ] [gl-vignette-background](https://github.com/mattdesl/gl-vignette-background)
- [ ] [stringify-clone](https://github.com/ahmadnassri/stringify-clone)
- [ ] [testdata-w3c-json-form](https://github.com/LinusU/testdata-w3c-json-form)
- [ ] [simple-media-element](https://github.com/Jam3/simple-media-element)
- [ ] [standard-json](https://github.com/flet/standard-json)
- [ ] [studynotes](https://github.com/feross/studynotes)
- [ ] [webtorrent-desktop](https://github.com/webtorrent/webtorrent-desktop)

**Comment by flipxfx** [comment]
So what are the next steps? Is that a reasonable amount? Would obviously need a breaking version bump.

**Comment by justinkalland** [comment]
I am a newer contributor here. But from what I have seen the next step is having consensus to include this addition. It appears consensus is achieved by input from the community with the final decision by the maintainers. I love Standard but would like to see a better process for proposing and adopting changes within the community. It is something I have been thinking about and planned on bringing up in the main repo. And to me it is necessary for Standard to reach its full potential as the _standard_.

**Comment by LinusU** [comment]
> I love Standard but would like to see a better process for proposing and adopting changes within the community. It is something I have been thinking about and planned on bringing up in the main repo. And to me it is necessary for Standard to reach its full potential as the standard.

Agreed 👍, we should also formalize the release process as well!

> Here are the failing repos:

I've updated `testdata-w3c-json-form` so that should pass now...

It seems like a lot of the packages are maintained by @feross, so it would be great if he could weigh in on what he thinks about the rule. If he is 👍 then I think we should start sending pull requests to failing repos, and then merging this (e.g. like in #124)

**Comment by feross** [comment]
This change will be included in `standard` 13.

I updated all the packages I have push access to, but there still remain several packages that need an update. It would be great if those who are interested in this change on this thread could send PRs to these repos! (In the meantime, I disabled the tests against these repos which is not ideal)

**Pull request merged**
