### PR TITLE
Add rule no-void

### PR DESCRIPTION
**Pull request by acarballo-cs**
Avoid useless void operator

### CODE REVIEW

**Comment by LinusU** [comment]
Sounds good to me, I don't really see when one would need it 🤔

**Comment by feross** [comment]
This sounds good to me. Only one repo was failing and it was an easy fix: https://github.com/feross/chrome-net/commit/8cc2520c0526362a0732c3e48d2dc7a2b60dc94b

Let's release this in `standard` 14.

**Comment by mightyiam** [comment]
I was just recently contemplating whether there are useful usages of `void`. Do you feel like the ESLint rule doc lists all them? I never used it, even once. So I'd probably not miss it. Yet, I'm still wondering. How about [non-leaky arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void#Non-leaking_Arrow_Functions)?

**Comment by feross** [comment]
`void` is used so rarely and there are better alternatives, so it's probably easier to just ban it so most folks won't even have to learn what it is.

If I have to make an argument for `void`, I agree that non-leaky arrow functions is a reasonable one:

```js
button.onclick = () => void doSomething()
```

However, you can do this with the same number of characters:

```js
button.onclick = () => { doSomething() }
```

And this avoids the need to understand a new concept. So it's clearer, IMO.

**Comment by mightyiam** [comment]
No argument here.

**Comment by Jessidhia** [comment]
I find `void` to be a more elegant solution to the "semicolon prefix" workaround to the ASI problem.

```ts
void (() => { /* some iife */ })()
// vs
;(() => { /* another iife */ })()
```

but this is kind of a style choice.

**Comment by nolanlawson** [comment]
I use `void 0` as a shorthand for `undefined`, but this is probably confusing and something I should stop doing anyway. Especially given that `undefined` can't be redefined anymore. :+1:

**Comment by feross** [comment]
> Especially given that `undefined` can't be redefined anymore. 👍

Yep! So happy about this change!

**Pull request merged**
