### PR TITLE
Add rule no-case-declarations

### PR DESCRIPTION
**Pull request by justinkalland**
Adds the rule `no-case-declarations`.

Ecosystem impact:
```
1..186
# tests 186
# pass  185
# fail  1
```

**Failing packages:**
- [x] [bittorrent-tracker](https://github.com/webtorrent/bittorrent-tracker) (webtorrent/bittorrent-tracker#305)

**References:**
- [ESLint documentation for no-case-declarations](https://eslint.org/docs/rules/no-case-declarations)
- Closes standard/standard#1211

### CODE REVIEW

**Comment by feross** [comment]
One repo started failing, but I PR'd it: https://github.com/zensh/resp.js/pull/3

**Comment by feross** [comment]
Let's ship this in `standard` v14

**Comment by feross** [comment]
@mightyiam Yeah, this blew my mind as well when I discovered it. Now I always use blocks in case statements.

**Comment by feross** [comment]
@justinkalland Btw, thanks for the pull request! You're awesome! 🤩

giphy

**Comment by ungoldman** [comment]
Just discovered this rule from upgrading to standard 14 and grumbled until I read https://eslint.org/docs/rules/no-case-declarations and learned something new. Thank you! I feel like each of these rules deserves its own class or blog or something, so much to learn about here. Okay good night 👋

**Comment by feross** [comment]
@ungoldman Indeed! Perhaps we can add such explanations to the `RULES.md` file!

**Pull request merged**
